(() => {
  const $ = (id) => document.getElementById(id); const el = { url: $("url"), model: $("model"), type: $("type"), token: $("token"), start: $("start"), stop: $("stop"), clear: $("clear"), status: $("status"), message: $("message"), final: $("final"), partial: $("partial"), format: $("format") };
  let ws, stream, context, source, node, mute, resampler, queue = new Float32Array(0), stopping = false;
  const set = (state, recording) => { el.status.textContent = state; el.start.disabled = recording; el.stop.disabled = !recording; for (const input of [el.url, el.model, el.type, el.token]) input.disabled = recording; };
  const message = (text) => { el.message.textContent = text; };
  function closeAudio() { node?.disconnect(); source?.disconnect(); mute?.disconnect(); stream?.getTracks().forEach((track) => track.stop()); if (context?.state !== "closed") context?.close(); stream = context = source = node = mute = resampler = undefined; queue = new Float32Array(0); }
  function append(text) { const span = document.createElement("span"); span.textContent = text; el.final.append(span, document.createTextNode(" ")); }
  function sendConverted(input) { const converted = resampler.process(input); const joined = new Float32Array(queue.length + converted.length); joined.set(queue); joined.set(converted, queue.length); queue = joined; const size = Math.round(resampler.outputRate / 50); while (queue.length >= size && ws?.readyState === WebSocket.OPEN) { ws.send(float32ToPcm16(queue.slice(0, size))); queue = queue.slice(size); } }
  async function connect() {
    if (!el.token.value.trim()) throw new Error("توکن را وارد کنید."); const url = new URL(el.url.value.trim()); if (!/^wss?:$/.test(url.protocol)) throw new Error("آدرس WebSocket معتبر نیست.");
    stopping = false; set("در حال اتصال…", true); message("اجازهٔ میکروفون و احراز هویت…");
    stream = await navigator.mediaDevices.getUserMedia({ video: false, audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true, sampleRate: 44100 } }); context = new AudioContext(); await context.resume(); await context.audioWorklet.addModule("worklet.js");
    ws = await new Promise((resolve, reject) => { const socket = new WebSocket(url); const timer = setTimeout(() => reject(new Error("اتصال به سرور زمان‌بر شد.")), 10000); socket.onopen = () => { clearTimeout(timer); resolve(socket); }; socket.onerror = () => { clearTimeout(timer); reject(new Error("اتصال WebSocket برقرار نشد.")); }; });
    const auth = await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error("پاسخ احراز هویت دریافت نشد.")), 10000); ws.onmessage = (event) => { try { const data = JSON.parse(event.data); if (data.status === "authorized") { clearTimeout(timer); resolve(data); } else if (data.error) { clearTimeout(timer); reject(new Error(data.error)); } } catch { reject(new Error("پاسخ نامعتبر از سرور.")); } }; ws.send(JSON.stringify({ config: { model: el.model.value, type: el.type.value, token: el.token.value.trim() } })); });
    resampler = new StreamingResampler(context.sampleRate, auth.sample_rate); resampler.outputRate = auth.sample_rate; el.format.textContent = `${context.sampleRate}Hz → ${auth.sample_rate}Hz · PCM16 · mono`;
    source = context.createMediaStreamSource(stream); node = new AudioWorkletNode(context, "capture-processor", { channelCount: 1, numberOfInputs: 1, numberOfOutputs: 1 }); mute = context.createGain(); mute.gain.value = 0; node.port.onmessage = ({ data }) => { if (!stopping) sendConverted(data); }; source.connect(node); node.connect(mute); mute.connect(context.destination);
    ws.onmessage = (event) => { try { const data = JSON.parse(event.data); if (typeof data.partial === "string") el.partial.textContent = data.partial || "—"; if (typeof data.text === "string" && data.text.trim()) { append(data.text.trim()); el.partial.textContent = "—"; } } catch {} }; ws.onclose = () => { if (!stopping) { closeAudio(); set("قطع شد", false); message("ارتباط قطع شد."); } }; set("در حال ضبط", true); message(`مدل ${auth.model} تأیید شد.`);
  }
  function stop() { if (stopping) return; stopping = true; node?.disconnect(); source?.disconnect(); mute?.disconnect(); stream?.getTracks().forEach((track) => track.stop()); context?.close(); if (queue.length && ws?.readyState === WebSocket.OPEN) ws.send(float32ToPcm16(queue)); if (ws?.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ eof: 1 })); set("آماده", false); message("نتیجهٔ نهایی در حال دریافت است."); setTimeout(() => ws?.close(), 3000); }
  el.start.onclick = () => connect().catch((error) => { stopping = true; ws?.close(); closeAudio(); set("خطا", false); message(error.message); }); el.stop.onclick = stop; el.clear.onclick = () => { el.final.textContent = ""; el.partial.textContent = "—"; };
})();
